// <auto-generated />
using System;
using Educobros.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Educobros.Migrations
{
    [DbContext(typeof(EduCobrosContext))]
    partial class EduCobrosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduCobros.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mensualidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MesesDebidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grado = "4to Primaria",
                            Mensualidad = 4500m,
                            MesesDebidos = 0,
                            Nombre = "María García Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Grado = "6to Primaria",
                            Mensualidad = 4500m,
                            MesesDebidos = 2,
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            Id = 3,
                            Grado = "2do Sec.",
                            Mensualidad = 5200m,
                            MesesDebidos = 0,
                            Nombre = "Ana Martínez Díaz"
                        },
                        new
                        {
                            Id = 4,
                            Grado = "3ro Sec.",
                            Mensualidad = 5200m,
                            MesesDebidos = 4,
                            Nombre = "Luis Hernández"
                        },
                        new
                        {
                            Id = 5,
                            Grado = "1ro Primaria",
                            Mensualidad = 3800m,
                            MesesDebidos = 0,
                            Nombre = "Sofía Reyes Guzmán"
                        });
                });

            modelBuilder.Entity("EduCobros.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("EduCobros.Models.Pago", b =>
                {
                    b.HasOne("EduCobros.Models.Estudiante", "Estudiante")
                        .WithMany("Pagos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("EduCobros.Models.Estudiante", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
